FROM kalilinux/kali-rolling

MAINTAINER cleverdj <cleverpdj@gmail.com>

# Install Kali Full
RUN rm -fR /var/lib/apt/ && \
    apt-get clean && \
    apt-get update -y && \
    apt-get install -y metasploit-framework && \

# Some system tools
RUN apt-get install -y colordiff colortail unzip vim tmux xterm zsh curl telnet strace ltrace tmate less build-essential wget python-pip python3-setuptools python3-pip tor proxychains proxychains4 zstd net-tools bash-completion iputils-tracepath npm yarnpkg

# Hack Tools
RUN apt-get install -y nmap sqlmap nikto lynis wpscan

# XSStrike
RUN git clone https://github.com/s0md3v/XSStrike.git && \
    cd XSStrike && \
    pip3 install -r requirements.txt

# BlackWidow
RUN git clone https://github.com/1N3/BlackWidow.git && \
    cd BlackWidow && \
    pip install -r requirements.txt


# Update DB and clean'up!
RUN updatedb && \
    apt-get autoremove -y && \
    apt-get clean 

# Welcome message
RUN echo "echo 'Kali full container!\n\n- If you need proxychains over Tor just activate tor service with:\n$ service tor start\n'" >> /etc/profile

CMD ["/bin/bash", "--init-file", "/etc/profile"]
